name: Deploy HTML to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: EC2_HOST

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check secrets
      run: |
        echo "EC2_HOST set? ${EC2_HOST:+yes}"
        echo "EC2_USER set? ${EC2_USER:+yes}"
        echo "EC2_KEY set? ${EC2_KEY:+yes}"
        echo "EC2_PASSPHRASE set? ${EC2_PASSPHRASE:+yes}"

    - name: Copy HTML to EC2 /tmp
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        passphrase: ${{ secrets.EC2_PASSPHRASE }}
        source: "index.nginx-debian.html"
        target: "/tmp/index.nginx-debian.html"

    - name: Move HTML into Nginx and reload
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        passphrase: ${{ secrets.EC2_PASSPHRASE }}
        script: |
          echo "✅ Connected to EC2"

          # Remove old file safely
          sudo rm -f /var/www/html/index.nginx-debian.html

          # Move new file into place
          sudo mv /tmp/index.nginx-debian.html /var/www/html/index.nginx-debian.html

          # Set ownership and permissions
          sudo chown www-data:www-data /var/www/html/index.nginx-debian.html
          sudo chmod 644 /var/www/html/index.nginx-debian.html

          # Reload Nginx
          sudo systemctl reload nginx

          echo "✅ Deployment complete!"
